In [1]:
import pandas as pd
One_piece = pd.read_html("https://en.wikipedia.org/wiki/One_Piece_(TV_series)")

In [2]:
len(One_piece)

26

In [7]:
One_piece[2]

   Season                                       Season title Episodes  \
   Season                                       Season title Episodes
0       1                                       East Blue[4]       61
1       2                       Entering into the Grand Line       16
2       3           Introducing Chopper at the Winter Island       14
3       4              Arrival & Fierce Fighting in Alabasta       39
4       5  Dreams!, The Zenny Pirate Crew Sortie!, Beyond...       13
5       6             Sky Island ~ Skypiea & The Golden Bell       52
6       7  Escape! The Marine Fortress & The Foxy Pirate ...       33
7       8                                        Water Seven       35
8       9                                        Enies Lobby       73
9      10                                      Thriller Bark       45
10     11                                Sabaody Archipelago       26
11     12                                    Island of Women       14
12     13                                         Impel Down       35
13     14                                         Marineford       60
14     15                                     Fishman Island       62
15     16                                        Punk Hazard       50
16     17                                          Dressrosa      118
17     18                                                Zou       36
18     19                                  Whole Cake Island      109
19     20                                       Wano Country      182

                Originally aired
   Episodes.1        First aired          Last aired
0          61   October 20, 1999      March 14, 2001
1          16     March 21, 2001     August 19, 2001
2          14    August 26, 2001    December 9, 2001
3          39  December 16, 2001    October 27, 2002
4          13   November 3, 2002    February 2, 2003
5          52   February 9, 2003       June 13, 2004
6          33      June 20, 2004      March 27, 2005
7          35     April 17, 2005      April 30, 2006
8          73       May 21, 2006   December 23, 2007
9          45    January 6, 2008   December 14, 2008
10         26  December 21, 2008       June 28, 2009
11         14       July 5, 2009    October 11, 2009
12         35   October 18, 2009       June 20, 2010
13         60      July 27, 2010  September 25, 2011
14         62    October 2, 2011   December 23, 2012
15         50    January 6, 2013    January 12, 2014
16        118   January 19, 2014       June 19, 2016
17         36      June 26, 2016       April 2, 2017
18        109      April 9, 2017       June 30, 2019
19        182       July 7, 2019                 TBA